### PR TITLE
[DOC-REVIEW] Welcome tutorial: add "Creating Virtual Environments in Jupyter Notebook" & refer to CondaVirtualEnv [IG-11333; IG-10216]

### PR DESCRIPTION
**Pull request by Sharon-iguazio**
@adiso75 @yaronha 
1. I edited the **GettingStarted/CondaVirtualEnv.ipynb** notebook.
2. In the **Welcome.ipynb** notebook (and **README.md**), I added a **Creating Virtual Environments in Jupyter Notebook** section under **Jupyter Notebook Basics**, which refers to the **CondaVirtualEnv** tutorial.

### CODE REVIEW

**Comment by Sharon-iguazio** [comment]
@adiso75 Note especially that in Step 3 of the "Setting Up a Virtual Environment Using conda" section of the **CondaVirtualEnv** tutorial, I edited the `install` command to add `-n <environment name>` (based on the [conda doc](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html).

**Comment by Sharon-iguazio** [comment]
I'm merging the PR to allow new PRs that include these changes, but it still requires review.

**Comment by adiso75** [comment]
@Sharon-iguazio 
Need to add the following:
When exporting the conda env the command should specify the env name so it should be (need to add -n env name)
conda env export  -n <env name> > /v3io/users/$V3IO_USERNAME/virtual_env/myenv.yaml

**Comment by Sharon-iguazio** [comment]
@adiso75 the requested changes were done in PR #41.

**Pull request merged**
